// Canonical VF-0033-00 GMP checklist content, in section order.
module.exports = [
  ["Employee Practices (All Areas)", [
    "Employees are following good hand washing procedures.",
    "Employees are not wearing jewelry or nail polish and all items are below the waist.",
    "No evidence of employees chewing gum or eating out on the lines.",
    "No personal items (phones, keys, wallets) in GMP areas",
    "Employees are wearing hairnets and beardnets properly. Wound(s) are covered with bandaged protected with rubber gloves.",
  ]],
  ["Production: PET 1, HuskyFiller/Cappers/Cap Hopper/Labeler/Case Packer/Palletizer", [
    "Production areas are orderly and not used for storage of extraneous materials; all parts, tools, and components are stored off the floor.",
    "Trash containers are available at points of use, covered where required, and not overflowing.",
    "Cleaning tools (squeegees, brooms, shovels, brushes) are properly stored and kept off the floor when not in use.",
    "Hoses are wound, hung properly, capped where applicable, and not left on the floor.",
    "Glass enclosure of the filler room is intact and free from cracks, chips, or other damage.",
    "Glass panels, joints, seals, light covers, and protective shields are secure and undamaged.",
    "Brittle materials (plastic guards, covers, housings) on production and molding equipment are intact and in good condition.",
    "No loose glass, brittle plastic, or fragments are observed on equipment, floors, or surrounding areas.",
    "Preform Bay Area, fillers, cappers, cap hoppers, conveyors, and associated equipment are clean, sanitary, and suitable for use.",
    "Utensils and small tools are properly stored and not placed on ladders, equipment, rails, or cap hoppers.",
    "Pens used in production areas are click-style or otherwise GMP-compliant (no removable caps).",
    "Doors in the filler room are closed and secured; CIP water valves are closed when not in use.",
    "Caps are not left in cap hoppers when the production line is not running.",
    "Chemical spray bottles are properly labeled, capped, and stored appropriately.",
    "Boxes of caps and labels are stored off the floor and protected from contamination.",
    "Bottles are protected from contamination immediately after forming; scrap and regrind are controlled and stored in designated containers.",
    "Production and plastic molding areas are clean, orderly, and free from unnecessary materials.",
    "Floors are free of resin, plastic scrap, debris, and buildup.",
    "Resin materials are stored off the floor, properly identified, and protected from contamination.",
    "Only approved resin materials are present and in use in the area.",
    "No oil, grease, or hydraulic leaks are observed on or around equipment.",
    "Molds and forming components are clean, intact, and free from buildup or foreign material.",
  ]],
  ["Production: PET 2, HuskyFiller/Cappers/Cap Hopper/Labeler/Case Packer/Palletizer", [
    "Production areas are orderly and not used for storage of extraneous materials; all parts, tools, and components are stored off the floor.",
    "Trash containers are available at points of use, covered where required, and not overflowing.",
    "Cleaning tools (squeegees, brooms, shovels, brushes) are properly stored and kept off the floor when not in use.",
    "Hoses are wound, hung properly, capped where applicable, and not left on the floor.",
    "Glass enclosure of the filler room is intact and free from cracks, chips, or other damage.",
    "Glass panels, joints, seals, light covers, and protective shields are secure and undamaged.",
    "Brittle materials (plastic guards, covers, housings) on production and molding equipment are intact and in good condition.",
    "No loose glass, brittle plastic, or fragments are observed on equipment, floors, or surrounding areas.",
    "Preform Bay Area, fillers, cappers, cap hoppers, conveyors, and associated equipment are clean, sanitary, and suitable for use.",
    "Utensils and small tools are properly stored and not placed on ladders, equipment, rails, or cap hoppers.",
    "Pens used in production areas are click-style or otherwise GMP-compliant (no removable caps).",
    "Doors in the filler room are closed and secured; CIP water valves are closed when not in use.",
    "Caps are not left in cap hoppers when the production line is not running.",
    "Chemical spray bottles are properly labeled, capped, and stored appropriately.",
    "Boxes of caps and labels are stored off the floor and protected from contamination.",
    "Bottles are protected from contamination immediately after forming; scrap and regrind are controlled and stored in designated containers.",
    "Production and plastic molding areas are clean, orderly, and free from unnecessary materials.",
    "Floors are free of resin, plastic scrap, debris, and buildup.",
    "Resin materials are stored off the floor, properly identified, and protected from contamination.",
    "Only approved resin materials are present and in use in the area.",
    "No oil, grease, or hydraulic leaks are observed on or around equipment.",
    "Molds and forming components are clean, intact, and free from buildup or foreign material.",
  ]],
  ["Water Processing Area (RO / Filtration / Mineral Injection / Utilities)", [
    "Water processing areas are clean, orderly, and free from unnecessary or extraneous materials.",
    "Floors are clean, dry, and free of standing water, residue, or buildup.",
    "Tanks, piping, manifolds, and valves are clean, intact, and in good condition.",
    "All pipe connections, fittings, and valves are leak-free with no visible drips or seepage.",
    "Hoses are properly connected during use, capped where applicable, and stored off the floor when not in use.",
    "Filters, membranes, housings, and strainers are installed correctly and intact.",
    "Chemical and mineral injection points are clean, secure, and protected from contamination.",
    "Gauges, meters, sight glasses, indicators, and control panels are intact, readable, and functioning.",
    "CIP connections and water valves are secure and not in use unless actively cleaning.",
    "No cross-connections or improper hose routing are observed.",
    "In-process tanks are closed, covered, and protected from contamination.",
    "Cleaning tools used in the water processing area are stored properly and segregated as required.",
    "Light fixtures, covers, and overhead structures do not pose a contamination risk to water or equipment.",
  ]],
  ["Compressor and Chiller", [
    "Utility systems area (compressors and chillers) is clean, orderly, and free from unnecessary or extraneous materials.",
    "Floors are clean, dry, and free of oil, grease, water, condensate, or debris.",
    "Compressors, chillers, air dryers, receivers, and associated utility equipment are clean and in good operating condition.",
    "No oil, air, water, refrigerant, or condensate leaks are observed from equipment, piping, hoses, or connections.",
    "Lubricants, refrigerants, oils, and maintenance chemicals are properly stored",
  ]],
  ["Warehouse (Materials Receiving, Storage & Distribution)", [
    "Forklift bays and material handling areas are clean, clearly designated, and free from unnecessary materials.",
    "No finished product, packaging, or ingredients are stored in forklift parking or charging areas.",
    "Forklifts, charging or fueling equipment, and associated areas are in good condition with no oil, hydraulic, or battery leaks.",
    "Dock doors and warehouse entry doors are closed when not in use, seal properly, and are in good condition (seals, bumpers, levelers).",
    "Dock, receiving, and warehouse floors are clean, dry, and free of trash, debris, or standing water.",
    "Incoming materials are protected during unloading and are free from visible damage, contamination, or infestation.",
    "Non-conforming or rejected materials are clearly identified and physically segregated from acceptable materials.",
    "All materials are stored off the floor on pallets or slip sheets, with a minimum 18-inch clearance from walls maintained.",
    "Pallets are clean, intact, and do not pose a contamination risk.",
    "Materials are clearly identified, protected, and stored to support FIFO and proper stock rotation.",
    "Cleaning tools are stored off the floor in designated locations; trash containers are covered and not overflowing.",
    "No food, drinks, or personal items are stored in warehouse product or material storage areas.",
    "No evidence of pest activity, harborage conditions, or unsealed entry points is observed.",
  ]],
  ["Chemical, Mineral & Non-Product Material Storage", [
    "Chemical and mineral storage areas are clean, organized, and designated.",
    "Access to chemical storage areas is controlled.",
    "Chemical containers are properly labeled, capped, and not leaking.",
    "Chemicals and minerals are stored off the floor on pallets or shelves.",
    "Chemicals, lubricants, and maintenance materials are segregated from product and packaging.",
    "Mineral containers and bags are intact and properly stored.",
    "No chemical spills, residues, or buildup observed.",
  ]],
  ["Laboratory", [
    "Laboratory areas are clean, orderly, and free of unnecessary clutter or unused materials.",
    "No food, drinks, or personal items are present in laboratory work or sample handling areas.",
    "Samples are properly labeled, identified, and controlled to prevent mix-ups or contamination.",
    "Reagents, media, and laboratory chemicals are clearly labeled and within expiration or use-by date.",
    "Glassware is clean, intact, and stored properly to prevent contamination or damage.",
    "Laboratory equipment is clean, maintained, and in good working condition.",
    "Laboratory waste containers are properly labeled, appropriate for the waste type, and not overflowing.",
  ]],
  ["Main Office Area", [
    "Main office areas are clean, orderly, and free of unnecessary clutter or unused materials.",
    "Floors, desks, cabinets, and work surfaces are clean and maintained to prevent dust or debris accumulation.",
    "No ingredients, packaging materials, finished product, samples, or production tools are stored in the main office area.",
    "Office waste containers are appropriate for use, covered where required, and not overflowing.",
    "Contractors, service personnel, and visitors sign the GMP log and acknowledge GMP requirements before being granted access to GMP-controlled areas.",
  ]],
];
